package com.dwitech.eap.stripe.payments.boundary;

import com.dwitech.eap.stripe.payments.control.Payments;
import com.dwitech.eap.stripe.payments.entity.CreatePaymentRequest;
import com.dwitech.eap.stripe.payments.entity.UpdatePaymentRequest;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.eclipse.microprofile.openapi.annotations.Operation;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponses;
import org.eclipse.microprofile.openapi.annotations.tags.Tag;

import javax.inject.Inject;
import javax.ws.rs.*;
import javax.ws.rs.core.Response;

import static com.dwitech.eap.stripe.payments.control.Validator.emptyParameter;
import static javax.json.Json.createObjectBuilder;
import static javax.ws.rs.core.MediaType.APPLICATION_JSON;
import static javax.ws.rs.core.Response.Status.BAD_REQUEST;
import static javax.ws.rs.core.Response.status;

@Path("/ac")
@Produces(APPLICATION_JSON)
@Consumes(APPLICATION_JSON)
@Tag(name = "Automatic confirmation service", description = "Return the client secret generated by the Stripe platform for a payment request for automatic confirmation")
public class AutomaticConfirmationEndpoint {
    @ConfigProperty(name = "stripe.currency") String defaultCurrency;
    @ConfigProperty(name = "stripe.secret.key") String secretKey;
    @Inject Payments payments;

    @POST @Path("/create")
    @Operation(description = "Start the process of a particular payment request")
    @APIResponse(responseCode = "200", description = "Successful, returning the client secret for this payment request")
    @APIResponse(responseCode = "400", description = "Error, the transaction amount was 0, missing from the request or was not in a valid format")
    @APIResponse(responseCode = "500", description = "Error, there was a problem notified by the Stripe service")
    public Response confirmPaymentFromHttpPostRequest(final CreatePaymentRequest request) {
        return payments.confirmPayment(request);
    }

    @GET @Path("/create")
    @Operation(description = "Start the process of a particular payment request")
    @APIResponse(responseCode = "200", description = "Successful, returning the client secret for this payment request")
    @APIResponse(responseCode = "400", description = "Error, the transaction amount was 0, missing from the request or was not in a valid format")
    @APIResponse(responseCode = "500", description = "Error, there was a problem notified by the Stripe service")
    public Response confirmPaymentFromHttpGetRequest(@QueryParam("amount") final double amount, @QueryParam("currency") String currency) {
        try {
            if (emptyParameter(amount)) {
                return status(BAD_REQUEST)
                        .entity(createObjectBuilder().add("message", "transaction amount is required")
                        ).build();
            }

            currency = emptyParameter(currency) ? defaultCurrency : currency;
            return payments.confirmPayment(new CreatePaymentRequest(amount, currency));
        } catch (NumberFormatException nfExc) {
            return status(BAD_REQUEST)
                    .entity(createObjectBuilder().add("message", "transaction amount was invalid")
                    ).build();
        }
    }

    @POST @Path("/update")
    @Operation(description = "Update the amount of a particular payment request")
    @APIResponses({
            @APIResponse(responseCode = "200", description = "Successful, returning the client secret for this payment request"),
            @APIResponse(responseCode = "400", description = "Error, the transaction amount was 0, missing from the request or was not in a valid format"),
            @APIResponse(responseCode = "400", description = "Error, the payment intent identifier was missing from the request"),
            @APIResponse(responseCode = "500", description = "Error, there was a problem notified by the Stripe service")
    })
    public Response updatePaymentFromHttpPostRequest(UpdatePaymentRequest request) {
        return payments.updatePayment(request);
    }

    @GET @Path("/update")
    @Operation(description = "Update the amount of a particular payment request")
    @APIResponses({
            @APIResponse(responseCode = "200", description = "Successful, returning the client secret for this payment request"),
            @APIResponse(responseCode = "400", description = "Error, the transaction amount was 0, missing from the request or was not in a valid format"),
            @APIResponse(responseCode = "400", description = "Error, the payment intent identifier was missing from the request"),
            @APIResponse(responseCode = "500", description = "Error, there was a problem notified by the Stripe service")
    })
    public Response updatePaymentFromHttpGetRequest(@QueryParam("amount") final double amount, @QueryParam("currency") String currency, @QueryParam("payId") String paymentIntentId) {
        try {
            if (emptyParameter(amount)) {
                return status(BAD_REQUEST)
                               .entity(createObjectBuilder().add("message", "transaction amount is required")
                               ).build();
            }

            if (emptyParameter(paymentIntentId)) {
                return status(BAD_REQUEST)
                               .entity(createObjectBuilder().add("message", "paymentIntentId is required")
                               ).build();
            }

            currency = emptyParameter(currency) ? defaultCurrency : currency;
            return payments.updatePayment(new UpdatePaymentRequest(amount, currency, paymentIntentId));
        } catch (NumberFormatException nfExc) {
            return status(BAD_REQUEST)
                           .entity(createObjectBuilder().add("message", "transaction amount was invalid")
                           ).build();
        }
    }
}
